spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: company

mongock:
  enabled: true
  runner-type: "InitializingBean"
  migration-scan-package: ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    io.mongock: DEBUG