create table authors (
                         id bigint generated by default as identity primary key,
                         full_name varchar(255) not null
);

create table genres (
                        id bigint generated by default as identity primary key,
                        name varchar(255) not null
);

create table books (
                       id bigint generated by default as identity primary key,
                       title varchar(255) not null,
                       author_id bigint references authors(id) on delete cascade
);

create table books_genres (
                              book_id bigint references books(id) on delete cascade,
                              genre_id bigint references genres(id) on delete cascade,
                              primary key (book_id, genre_id)
);