-- Таблицы приложения
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
    );

CREATE TABLE IF NOT EXISTS authors (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       full_name VARCHAR(255),
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_authors_user FOREIGN KEY (user_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS genres (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS books (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     title VARCHAR(255),
    author_id BIGINT,
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS books_genres (
                                            book_id BIGINT,
                                            genre_id BIGINT,
                                            PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_books_genres_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    CONSTRAINT fk_books_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(1000) NOT NULL,
    book_id BIGINT,
    CONSTRAINT fk_comments_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
    );

-- Таблицы Spring Security ACL
CREATE TABLE IF NOT EXISTS acl_sid (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       principal BOOLEAN NOT NULL,
                                       sid VARCHAR(100) NOT NULL,
    CONSTRAINT unique_acl_sid UNIQUE(sid, principal)
    );

CREATE TABLE IF NOT EXISTS acl_class (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         class VARCHAR(100) NOT NULL,
    CONSTRAINT unique_acl_class UNIQUE(class)
    );

CREATE TABLE IF NOT EXISTS acl_object_identity (
                                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   object_id_class BIGINT NOT NULL,
                                                   object_id_identity BIGINT NOT NULL,
                                                   parent_object BIGINT,
                                                   owner_sid BIGINT NOT NULL,
                                                   entries_inheriting BOOLEAN NOT NULL,
                                                   CONSTRAINT unique_acl_object_identity UNIQUE(object_id_class, object_id_identity),
    CONSTRAINT fk_acl_oi_class FOREIGN KEY(object_id_class) REFERENCES acl_class(id),
    CONSTRAINT fk_acl_oi_parent FOREIGN KEY(parent_object) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_oi_owner FOREIGN KEY(owner_sid) REFERENCES acl_sid(id)
    );

CREATE TABLE IF NOT EXISTS acl_entry (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         acl_object_identity BIGINT NOT NULL,
                                         ace_order INT NOT NULL,
                                         sid BIGINT NOT NULL,
                                         mask INTEGER NOT NULL,
                                         granting BOOLEAN NOT NULL,
                                         audit_success BOOLEAN NOT NULL,
                                         audit_failure BOOLEAN NOT NULL,
                                         CONSTRAINT unique_acl_entry UNIQUE(acl_object_identity, ace_order),
    CONSTRAINT fk_acl_entry_object FOREIGN KEY(acl_object_identity) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_entry_sid FOREIGN KEY(sid) REFERENCES acl_sid(id)
    );