spring:
  datasource:
    url: jdbc:h2:mem:maindb;MODE=LEGACY
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  data:
    mongodb:
      uri: mongodb://localhost:27017/library
      database: library
    rest:
      base-path: /data

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  shell:
    interactive:
      enabled: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, logfile, env, beans, mappings
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: Library Application
    description: Spring Boot Library with Actuator
    version: 1.0.0

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    ru.otus.hw: DEBUG